### PR TITLE
header component added

### PR DESCRIPTION
**Pull request by unnikrishnan2002**
## Related Issue 

- Issue was to added header section . Th same has been linked below

- [X] JWOC Participant
- [X] Contributor

Closes: #9 

### Describe the changes you've made

-> Navbar is added with underline hover effect for each link
-> Pull request template renamed according to convention

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The change has been reviewed on the local HTML website

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

image

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add [PR template](https://github.com/prathimacode-hub/Treksy/blob/main/.github/pullrequest_template.md) in this PR using edit option along with inclusion of your issue number and short detail of what u had added along with screenshot @unnikrishnan2002

**Review by prathimacode-hub — APPROVED** [review]
Hey, if you do changes now. Since this PR is open, it will merge into this. We can do the change after this PR is merged. For right now, you just add the PR template and add the details. @unnikrishnan2002

**Comment by unnikrishnan2002** [comment]
> Hey, if you do changes now. Since this PR is open, it will merge into this. We can do the change after this PR is merged. For right now, you just add the PR template and add the details. @unnikrishnan2002

Done I renamed the file and updated the PR message

**Comment by unnikrishnan2002** [comment]
> Congrats on your first PR. Well done. Welcome to the repo. Keep it up. 👏🎉@unnikrishnan2002

Thanks to you and @Swatilekha-Roy for helping me to do this 😄🎉

**Comment by prathimacode-hub** [comment]
You're welcome. Keep exploring. 😀@unnikrishnan2002

**Pull request merged**
