### PR TITLE
Added new fonts, and updated UI 

### PR DESCRIPTION
**Pull request by Anosh21**
## Related Issue 

- Info about the related issue 

- [x] JWOC Participant
- [x] Contributor

Closes: #24

## Changes-
- Made Responsive UI with help of media query [all resolutions compatibility]
-Added new font from google fonts,
- Executed Dark and light bg colors.

### CODE REVIEW

**Comment by unnikrishnan2002** [comment]
Hey @Anosh21 I believe that you have some more work to do . I see you just edited the about page . The issue was to make all the pages look like a part of the website . Like adding the header and footer in all the pages so that all the pages look like a part of the website

**Review by unnikrishnan2002 — COMMENTED** [review]
Hey @Anosh21 I believe that you have some more work to do . I see you just edited the about page . The issue was to make all the pages look like a part of the website . Like adding the header and footer in all the pages so that all the pages look like a part of the website

**Comment by Anosh21** [comment]
@unnikrishnan2002 Okay , I will add it, you can merge this one I will make another pull for those request.

**Comment by unnikrishnan2002** [comment]
> @unnikrishnan2002 Okay , I will add it, you can merge this one I will make another pull for those request.

Do it in this PR itself because the issue demands it . Also I can't merge your PR @prathimacode-hub will look into it and merge .

**Comment by prathimacode-hub** [comment]
Kindly work on the changes asap. @Anosh21

**Comment by prathimacode-hub** [comment]
@Anosh21 Kindly do the changes

**Comment by Anosh21** [comment]
Hey @prathimacode-hub you can merge now.

**Comment by prathimacode-hub** [comment]
It still tells that css/about.css file is conflicting to the existing code. Once make your forked repo even with the main repo. And then re-push your code again to resolve this conflict @Anosh21

**Comment by Anosh21** [comment]
LGTM!

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great start. Welcome to repo. Keep it up. 👏🎉@Anosh21

**Pull request merged**
