### PR TITLE
adding animation on scroll

### PR DESCRIPTION
**Pull request by ashutoshnautiyal7**
## Related Issue 

- Info about the related issue 

- [x] JWOC Participant
- [x] Contributor

Closes: #36 (issue-no:36)

Added animation particularly on About and Blogs page.
Library used for animation is AOS-Animation on Scroll. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add your issue number in your PR template along with the output screenshot after changes done in it. @ashutoshnautiyal7

**Comment by ashutoshnautiyal7** [comment]
I did the animation so can't add screenshot of the same!

**Comment by ashutoshnautiyal7** [comment]
> 

I did the animation part so adding screenshot won't show any difference .

**Comment by Swatilekha-Roy** [comment]
Great job so far, @ashutoshnautiyal7! Please add the animations across all pages- not just the "ABOUT US" page. Kindly make a new pr with those changes- and we will merge your pr! Thanks.

**Comment by Swatilekha-Roy** [comment]
@ashutoshnautiyal7 any updates?

**Comment by ashutoshnautiyal7** [comment]
Sorry I didn't received the mail earlier. I will do it by today.

**Comment by ashutoshnautiyal7** [comment]
forked the project again but can't find the other pages i.e contact us and
bookings, then how can I add animation there ?

**Pull request merged**
