### PR TITLE
added logo and fevicon

### PR DESCRIPTION
**Pull request by Shikha785**
## Related Issue 

- Make logo and fevicon.

- [x] JWOC Participant
- [x] Contributor

Closes: #10 

### Describe the changes you've made

Added logo and fevicon

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

fevicon1
fevicon2
fevicon3
logo1
logo2
logo3

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Reach out to me once. Have something to clarify. @Shikha785

**Comment by prathimacode-hub** [comment]
Have you updated the changes? @Shikha785

**Comment by Shikha785** [comment]
I request you to unassign me this issue .

**Comment by prathimacode-hub** [comment]
Why r u backing off? You had done the hard work but didn't address it as mentioned. It's a small change that needs to be done. @Shikha785

**Comment by prathimacode-hub** [comment]
@Shikha785, reply something?

**Comment by prathimacode-hub** [comment]
Approving the PR. Though no reply or asked for short change. I don't want your efforts to get wasted. @Shikha785

**Pull request merged**
