### PR TITLE
About Us page UI improved

### PR DESCRIPTION
**Pull request by itshypon**
## Related Issue 

In current version of About Us webpage, all the elements are un-organized. Title and footer everything is horizontally fixed. 

- [x] Hacktoberfest Participant
- [x] Contributor

Closes: #58

### Describe the changes you've made

I have changed the look of this page. I have used bootstrap to add navbar, adjusted position, padding and margin of main section. And adjusted footer horizontally though it look better than before.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have verified the changes by opening and doing changed locally

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
image
image

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Include the issue number in your PR commit message here :

Closes: #issue number that will be closed through this PR

@itshypon

**Comment by itshypon** [comment]
@prathimacode-hub Done

**Comment by itshypon** [comment]
@prathimacode-hub Kindly take a look at 'Review Required' or give it a hacktoberfest-accepted label so that it can be added in my profile. Thanks !

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good work. 👏👌@itshypon

**Pull request merged**
