### PR TITLE
Added a favicon to the website

### LINKED ISSUE #60: Add Favicon to the website
Currently, there is no favicon to the website, I want to add this.
This issue is opened under the hacktoberfest.

### PR DESCRIPTION
**Pull request by Laxmankohar**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest Participant
- [x] Contributor

Closes: #60 

### Describe the changes you've made

I have added a link inside the head tag of index.html.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

By looking at the url link of website. Original one donot contain favicon but  updated one contains.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
Screenshot (134) | Screenshot (137)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Where have you got this favicon from? @Laxmankohar

**Comment by Laxmankohar** [comment]
it was inside assets folder.

**Comment by prathimacode-hub** [comment]
The issue was assigned in a purpose that, a new favicon would be created for the webapp Treksy. @Laxmankohar

**Comment by Laxmankohar** [comment]
so, what type of favicon do you need? can you give some idea?

**Comment by prathimacode-hub** [comment]
Anything that depict the theme travel with colors that's used in webapp. @Laxmankohar

**Comment by Laxmankohar** [comment]
@prathimacode-hub  can you please check  the favicon attached below and let me know.


airplane
flight
globe
traveling

**Comment by prathimacode-hub** [comment]
Don't use just flight, travel can be anything. Favicon should depict it in generalized format not only flight related travel. @Laxmankohar

**Comment by Laxmankohar** [comment]
@prathimacode-hub Can you please check it again?

travel1
travel
travel(1)
travel2

**Comment by prathimacode-hub** [comment]
@Laxmankohar, update please?

**Comment by Laxmankohar** [comment]
> @Laxmankohar, update please?

i have already send you some more sample to select. I was waiting for your response. please do check above sample and let me know.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub can you please check the favicon attached below and let me know.
> 
> airplane flight globe traveling

In this, 1st one is good to go. @Laxmankohar

**Comment by Laxmankohar** [comment]
okkk

**Comment by Laxmankohar** [comment]
@prathimacode-hub  Can you please check it  and let me know, after that i will make a pull request.

image

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Well done.👌✔@Laxmankohar

**Pull request merged**
